name: Action Development CI

# Lightweight CI for action development - runs on every change
on:
  push:
    branches: [main, develop, feature/**]
  pull_request:
    branches: [main, develop]

# Minimal permissions for CI validation
permissions:
  contents: read
  actions: read

jobs:
  # Fast validation - no Oracle DB needed
  validate-action:
    name: Validate Action Structure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate action.yml syntax
        run: |
          echo "🔍 Validating action.yml structure..."

          # Check if action.yml exists and is valid YAML
          if ! python3 -c "import yaml; yaml.safe_load(open('action.yml'))" 2>/dev/null; then
            echo "❌ action.yml is not valid YAML"
            exit 1
          fi

          # Check required fields
          required_fields=("name" "description" "runs")
          for field in "${required_fields[@]}"; do
            if ! grep -q "^${field}:" action.yml; then
              echo "❌ Missing required field: ${field}"
              exit 1
            fi
          done

          echo "✅ action.yml structure is valid"

      - name: Check for shell script syntax
        run: |
          echo "🔍 Checking shell scripts..."
          find scripts/ -name "*.sh" -exec bash -n {} \; 2>/dev/null || {
            echo "❌ Shell script syntax errors found"
            exit 1
          }
          echo "✅ All shell scripts have valid syntax"

      - name: Validate README and documentation
        run: |
          echo "🔍 Checking documentation..."

          # Check if README exists
          if [[ ! -f README.md ]]; then
            echo "❌ README.md not found"
            exit 1
          fi

          # Check if action.yml is documented in README
          if ! grep -q "uses:.*oracledb-action" README.md; then
            echo "⚠️  README might be missing usage examples"
          fi

          echo "✅ Documentation checks passed"

  # Lint and format check - fast feedback
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: check # Don't auto-fix in CI

  # Minimal Oracle test - only on action changes
  smoke-test:
    name: Smoke Test (Oracle 21-slim)
    runs-on: ubuntu-latest
    # Only run if action files changed
    if: contains(github.event.head_commit.modified, 'action.yml') ||
      contains(github.event.head_commit.added, 'action.yml') ||
      startsWith(github.head_ref, 'feature/') ||
      github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Action - Basic Functionality
        uses: ./ # Test the local action
        with:
          oracle-version: 21-slim
          setup-scripts: examples/sql/setup/01_create_tables.sql
          test-scripts: examples/sql/tests/01_test_tables.sql
          cleanup-scripts: examples/sql/cleanup/01_cleanup_all.sql
          wait-timeout: 180 # Shorter timeout for CI
          run-checkov: false # Skip security scan for speed
