name: Debug Docker Availability

on:
  workflow_dispatch:

jobs:
  debug-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check Docker availability
        run: |
          echo "=== System Info ==="
          uname -a

          echo "=== PATH ==="
          echo $PATH

          echo "=== Which Docker ==="
          which docker || echo "Docker not in PATH"

          echo "=== Docker Location ==="
          ls -la /usr/bin/docker || echo "No docker in /usr/bin"
          ls -la /usr/local/bin/docker || echo "No docker in /usr/local/bin"

          echo "=== Docker Version ==="
          docker --version || echo "Docker command failed"

          echo "=== Docker Info ==="
          docker info || echo "Docker daemon not accessible"

          echo "=== Test Docker Run ==="
          docker run hello-world || echo "Docker run failed"
